apiVersion: v1
kind: Service
metadata:
  labels:
    app: bizsvc-develop
  name: bizsvc-develop
  namespace: jenkins
spec:
  ports:
  - port: 9010
    nodePort: 30010
    protocol: TCP
    targetPort: 9010
  selector:
    app: bizsvc-develop
  sessionAffinity: None
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: bizsvc-develop
  name: bizsvc-develop
  namespace: jenkins
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: bizsvc-develop
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: bizsvc-develop
    spec:
      containers:
      - image: harbor.t2cp.com/t2cp-dev/bizsvc-develop:latest
        imagePullPolicy: Always
        name: bizsvc-develop
        volumeMounts:
        - mountPath: /config.yml
          name: config
          subPath: config.yml
        - mountPath: /static/config.js
          name: config
          subPath: config.js
        resources: {}
      volumes:
      - configMap:
          name: config-develop
        name: config
      dnsPolicy: ClusterFirst
      nodeSelector:
        node: node108
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
