app:
  address: 0.0.0.0
  port: 9010
  kubeFile: /tmp/config
  page: 20

mysql:
  mysqlConnection: root:aaaaaa@(192.168.131.30:3306)/t2cp?charset=utf8&parseTime=True&loc=Local
  maxIdleConns: 1000
  maxOpenConns: 2000
  logMode: true

auth:
  allowAll: false
  ExpiresAt: 7200

rancher:
  Url:       "https://192.168.131.30:8443/v3"
  AccessKey: "token-dl496"
  SecretKey: "sr9ckff9czw6rldwrflnf2vh8l4zbjpxm7j76xl5cst9s47n9fhlgr"
  Insecure: true
  CertPath:  "rancher.cer"

websocket:
  Url:       "http://127.0.0.1:9010"
  Path:      "/api/v1/ws/"
  Token:     ""
  WebsocketShell:  "ws://127.0.0.1:9010/api/v1/ws/socket.io"

ignore:
  url: "/api/v1/login,/api/v1/logout,info,ws,misc,websocket"
